# Step 1: Use the base image provided
FROM svizor/zoomcamp-model:3.11.5-slim

# Step 2: Set the working directory inside the container
WORKDIR /app

# Step 3: Copy the Pipenv files and install dependencies
COPY ["Pipfile", "Pipfile.lock", "./"]
RUN pip install pipenv && pipenv install --ignore-pipfile

# Step 4: Copy your Flask application script and model files into the container
COPY ["app.py", "model1.bin", "dv.bin", "./"]

# Step 5: Expose the port the app runs on
EXPOSE 8000

# Step 6: Command to run the Flask app using Gunicorn
CMD ["pipenv", "run", "gunicorn", "-w", "4", "-b", "0.0.0.0:8000", "app:app"]
